### ISSUE TITLE
Bug: Release Build without vk validation crashes on startup

### ISSUE THREAD

**Issue by mlknz** [ExtinctionHD/SteelEngine#10]
Release build works with kValidationEnabled = true.
However, if this variable is set to false, build crashes on startup without any meaningful message.
All log is: [INFO] GPU selected: NVIDIA GeForce RTX 3080

**Comment by ExtinctionHD** [comment]
Probably this [commit](https://github.com/ExtinctionHD/SteelEngine/commit/a7272eba22b1a9760349c8601c3cefb1663d36bb) will help
